### ISSUE TITLE
Migrate npm package name to @improbable-eng/grpc-web

### ISSUE THREAD

**Issue by jonnyreeves** [improbable-eng/grpc-web#289]
## Overview
- [Google's grpc-web implementation](https://github.com/grpc/grpc-web) is published to npm as [`grpc-web`](https://www.npmjs.com/package/grpc-web)
- [Improbable's gprc-web implementation](https://github.com/improbable-eng/grpc-web) (this project) is published to npm as [`grpc-web-client`](https://www.npmjs.com/package/grpc-web-client)

To disambiguate the two, I propose that we migrate this project to publish under the `@improbable-eng` namespace in npm, ie: `@improbable-eng/grpc-web`, making use the npm [orgs](https://docs.npmjs.com/orgs/) feature.

## Migration Path
- [x] Rename and publish 0.8.0 under `@improbable-eng/grpc-web` on npm (#290)
- [x] Update mono-repo to remove all references to `grpc-web-client` package (#297)
- [x] Release a new version of ts-protoc-gen which generates code that imports `@improbable-eng/grpc-web` (improbable-eng/ts-protoc-gen#147)
- [x] Publish grpc-web-node-http-transport under the @improbable-eng org. (#299)
- [x] Deprecate the current `grpc-web-client` and `grpc-web-node-http-transport` packages with a note that encourages consumers to switch to `@improbable-eng` versions

Consumers would need to modify their import statements accordingly:

```
# Before
import { grpc } from 'grpc-web-client'

# After
import { grpc } from '@improbable-eng/grpc-web'
```

cc @easyCZ @johanbrandhorst @MarcusLongmuir

**Comment by jonny-improbable** [comment]
To get the ball rolling I've secured the `improbable-eng` org on npm

**Comment by jonny-improbable** [comment]
Step one complete, [published 0.8.0 of @improbable-eng/grpc-web to npm](https://www.npmjs.com/package/@improbable-eng/grpc-web)

**Comment by johanbrandhorst** [comment]
https://github.com/improbable-eng/ts-protoc-gen/blob/f1270468fc080e3b15e582892c589933d99af8f1/src/service/grpcweb.ts#L174

**Comment by johanbrandhorst** [comment]
https://github.com/improbable-eng/ts-protoc-gen/pull/147

**Comment by jonnyreeves** [comment]
ts-protoc-gen v0.9.0 has been released which code-gens import statements that use the `@improbable-eng/grpc-web` package.

**Comment by jonny-improbable** [comment]
```
jonny$ npm i grpc-web-node-http-transport
npm WARN deprecated grpc-web-node-http-transport@0.0.1: This package has been deprecated in favor of @improbable-eng/grpc-web-node-http-transport
```

**Comment by jonny-improbable** [comment]
OK, I've also deprecated the `grpc-web-client` package, and it's showing up on npm but not when I install it locally... 🤷‍♂️

Still, pretty sure we can now mark this migration as complete; I'll leave this issue open for a week to provide visibility to the community should anyone run into problems.

**Comment by johanbrandhorst** [comment]
So, uh, we've release 0.8.0 on NPM but we haven't got a corresponding release of this repo yet. How did we get out of sync like this? Can I make a release?

**Comment by johanbrandhorst** [comment]
Bump

**Comment by jonny-improbable** [comment]
This has been done for a long time 🥂
